name = "portfolio-cors-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGINS = "https://venaki.github.io,http://localhost:8080"

[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "f370ac88adaa46869285627952a7e542"

# GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET are set via `wrangler secret put`
